<a href="https://colab.research.google.com/github/akashgoyal-20/Machine-Learning-Assignments/blob/main/ML_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1: Questions on Basic NumPy Array

(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two NumPy in-built methods

(c) Compare the following numpy arrays:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

(d) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
i. Sum of all elements
ii. Sum of all elements row-wise
iii. Sum of all elements column-wise


(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
i. Sum of diagonal elements
ii. Eigen values of matrix
iii. Eigen vectors of matrix
iv. Inverse of matrix
v. Determinant of matrix

(g) Multiply the following matrices and also find covariance between matrices using NumPy:
i. p = [[1, 2], [2, 3]]
   q = [[4, 5], [6, 7]]
ii. p = [[1, 2], [2, 3], [4, 5]]
    q = [[4, 5, 1], [6, 7, 2]]

(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
find inner, outer and cartesian product?

In [50]:
import numpy as np

#a
arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed Array:", arr[::-1])



Reversed Array: [5 4 6 3 2 1]


In [49]:
#b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
print("Flatten (ravel):", array1.ravel())
print("Flatten (flatten):", array1.flatten())

Flatten (ravel): [1 2 3 2 4 5 1 2 3]
Flatten (flatten): [1 2 3 2 4 5 1 2 3]


In [48]:
#c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print(np.equal(arr1, arr2))

[[ True  True]
 [ True  True]]


In [47]:
#d
x = np.array([5,2,3,4,1,1,2,5,1,1])
x1, idx = np.unique(x, return_index=True)
count = np.unique(x, return_counts=True)

print(f"The most frequent element is {x1[0]} and its index is {idx[0]}")

The most frequent element is 1 and its index is 4


In [46]:
#e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Total Sum:", gfg.sum())
print("Row-wise Sum:", gfg.sum(axis=1))
print("Column-wise Sum:", gfg.sum(axis=0))

Total Sum: 45
Row-wise Sum: [[14]
 [16]
 [15]]
Column-wise Sum: [[20  9 16]]


In [45]:
#f
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
print("Diagonal Sum:", np.trace(n_array))
eig_vals, eig_vecs = np.linalg.eig(n_array)
print("Eigenvalues:", eig_vals)
print("Eigenvectors:\n", eig_vecs)
print("Inverse:\n", np.linalg.inv(n_array))
print("Determinant:", np.linalg.det(n_array))

Diagonal Sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [44]:
#g
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])

print("Matrix Multiply:\n", np.dot(p, q))
print("Covariance:\n", np.cov(p, q))


Matrix Multiply:
 [[16 19]
 [26 31]]
Covariance:
 [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [43]:
#h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

innerprod = np.inner(x, y)
print("Inner product:\n",innerprod)

outerprod = np.outer(x, y)
print("Outer product:\n",outerprod)

cartesian_product_p, cartesian_product_q = np.meshgrid(x, y)
cartesian_product = np.column_stack((cartesian_product_p.ravel(), cartesian_product_q.ravel()))
print(f"Cartesian product:\n{cartesian_product}")

Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
[[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]


Q2: Based on NumPy Mathematics and Statistics

(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])

i. Find element-wise absolute value

ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each row.

iii. Mean, Median and Standard Deviation of flattened array, of each column, and each row



In [42]:
#a
array=np.array([[1,-2,3],[-4,5,-6]])
abs_array=np.abs(array)
print("Absolute Values:\n",abs_array)
print()

flat=array.flatten()
print("Flattened Percentiles:")
print("25th:",np.percentile(flat,25))
print("50th:",np.percentile(flat,50))
print("75th:",np.percentile(flat,75))
print()

print("Column-wise Percentiles:")
print("25th:",np.percentile(array,25,axis=0))
print("50th:",np.percentile(array,50,axis=0))
print("75th:",np.percentile(array,75,axis=0))
print()

print("Row-wise Percentiles:")
print("25th:", np.percentile(array,25,axis=1))
print("50th:", np.percentile(array,50,axis=1))
print("75th:", np.percentile(array,75,axis=1))
print()

print("Mean (Flattened):",np.mean(flat))
print("Median (Flattened):",np.median(flat))
print("Std Dev (Flattened):",np.std(flat))
print()

print("Mean (Column-wise):",np.mean(array,axis=0))
print("Median (Column-wise):",np.median(array,axis=0))
print("Std Dev (Column-wise):",np.std(array,axis=0))
print()

print("Mean (Row-wise):",np.mean(array,axis=1))
print("Median (Row-wise):",np.median(array,axis=1))
print("Std Dev (Row-wise):",np.std(array,axis=1))



Absolute Values:
 [[1 2 3]
 [4 5 6]]

Flattened Percentiles:
25th: -3.5
50th: -0.5
75th: 2.5

Column-wise Percentiles:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]

Row-wise Percentiles:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]

Mean (Flattened): -0.5
Median (Flattened): -0.5
Std Dev (Flattened): 3.8622100754188224

Mean (Column-wise): [-1.5  1.5 -1.5]
Median (Column-wise): [-1.5  1.5 -1.5]
Std Dev (Column-wise): [2.5 3.5 4.5]

Mean (Row-wise): [ 0.66666667 -1.66666667]
Median (Row-wise): [ 1. -4.]
Std Dev (Row-wise): [2.05480467 4.78423336]


(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).

Find floor, ceiling and truncated value, rounded values

In [53]:
#b
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
floor_values = np.floor(a)
print("Floor values:",floor_values)

ceil_values = np.ceil(a)
print("Ceil values:",ceil_values)

trunc_values = np.trunc(a)
print("Truncated values:",trunc_values)

rounded_values_default = np.round(a) # Rounds to nearest integer
print("Rounded values (default):",rounded_values_default)

Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceil values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values (default): [-2. -2. -0.  0.  2.  2.  3.]


Q3: Searching and Sorting

(a) For the array array = np.array([10, 52, 62, 16, 16, 54, 453]), find:

i. Sorted array

ii. Indices of sorted array

iii. 4 smallest elements

iv. 5 largest elements

In [35]:
#a
array = np.array([10, 52, 62, 16, 16, 54, 453])
print("Sorted:", np.sort(array))
print("Indices of Sorted:", np.argsort(array))
print("4 Smallest:", np.partition(array, 4)[:4])
print("5 Largest:", np.sort(array)[-5:])

Sorted: [ 10  16  16  52  54  62 453]
Indices of Sorted: [0 3 4 1 5 2 6]
4 Smallest: [10 16 16 52]
5 Largest: [ 16  52  54  62 453]


(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find

i. Integer elements only

ii. Float elements only

In [55]:
#b
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integers = array[np.mod(array, 1) == 0]
floats = array[np.mod(array, 1) != 0]
print("Integers Elements:",integers)
print("Floats Elements:",floats)

Integers Elements: [1. 2. 3. 2.]
Floats Elements: [1.2 2.2]
